### ISSUE TITLE
How to download the animated version?

### ISSUE THREAD

**Issue by Markellas** [Tarikul-Islam-Anik/Animated-Fluent-Emojis#8]
HI! I love this emoji, but how to download them in a .gif format (animated)?

**Comment by Tarikul-Islam-Anik** [comment]
Hello,@Markellas!
All emojis are in **[Animated PNG (APNG)](https://en.wikipedia.org/wiki/APNG)**. Which means they are already in a animated format. APNG supports all the major browsers. Check browser compatibility score [here](https://www.lambdatest.com/web-technologies/apng). But there's some drawbacks. 

- If you send a APNG file as an attachment _(suppose sending a message in Twitter, Discord or other messaging services)_ it won't because of file compression.
- If you want to add them to an app development project like Flutter or React Native, it won't work.

You can download emojis in APNG format and convert APNG to GIF format in online, and I'll animate. but picture quality may decrease. You can try [Ezgif](https://ezgif.com/apng-to-gif), it works fine.

I hope that clears everything. If you have more queries, feel free to ask.

**Comment by Markellas** [comment]
> Hello,@Markellas! All emojis are in **[Animated PNG (APNG)](https://en.wikipedia.org/wiki/APNG)**. Which means they are already in a animated format. APNG supports all the major browsers. Check browser compatibility score [here](https://www.lambdatest.com/web-technologies/apng). But there's some drawbacks. 
> 
> * If you send a APNG file as an attachment _(suppose sending a message in Twitter, Discord or other messaging services)_ it won't because of file compression.
> * If you want to add them to an app development project like Flutter or React Native, it won't work.
> 
> You can download emojis in APNG format and convert APNG to GIF format in online, and I'll animate. but picture quality may decrease. You can try [Ezgif](https://ezgif.com/apng-to-gif), it works fine.
> 
> I hope that clears everything. If you have more queries, feel free to ask.

Thanks! I just didn't know it is APNG. I'll just use the converter to GIF to use them outside the browser!
